/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as LoggedinRouteImport } from "./routes/_loggedin"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as LoggedinAssessmentsIndexRouteImport } from "./routes/_loggedin/assessments/index"
import { Route as LoggedinAssessmentsUsersRouteImport } from "./routes/_loggedin/assessments/users"
import { Route as LoggedinAssessmentsOrganisationsRouteImport } from "./routes/_loggedin/assessments/organisations"
import { Route as LoggedinAssessmentsNewRouteImport } from "./routes/_loggedin/assessments/new"
import { Route as LoggedinAssessmentsDashboardRouteImport } from "./routes/_loggedin/assessments/dashboard"
import { Route as LoggedinAssessmentsAnalyticsRouteImport } from "./routes/_loggedin/assessments/analytics"
import { Route as LoggedinAssessmentsAdminGlobalRouteImport } from "./routes/_loggedin/assessments/admin-global"
import { Route as LoggedinAssessmentsRiskIndexRouteImport } from "./routes/_loggedin/assessments/risk/index"
import { Route as LoggedinAssessmentsOrganizationalIndexRouteImport } from "./routes/_loggedin/assessments/organizational/index"
import { Route as LoggedinAssessmentsCapacityIndexRouteImport } from "./routes/_loggedin/assessments/capacity/index"
import { Route as LoggedinAssessmentsRiskAdminRouteImport } from "./routes/_loggedin/assessments/risk/admin"
import { Route as LoggedinAssessmentsOrganizationalAdminRouteImport } from "./routes/_loggedin/assessments/organizational/admin"
import { Route as LoggedinAssessmentsCapacityAdminRouteImport } from "./routes/_loggedin/assessments/capacity/admin"
import { Route as LoggedinAssessmentsAssociationsProfileIdRouteImport } from "./routes/_loggedin/assessments/associations/$profileId"
import { Route as LoggedinAssessmentsProfileIdEditRouteImport } from "./routes/_loggedin/assessments/$profileId/edit"
import { Route as LoggedinAssessmentsRiskEvaluationIdIndexRouteImport } from "./routes/_loggedin/assessments/risk/$evaluationId/index"
import { Route as LoggedinAssessmentsOrganizationalEvaluationIdIndexRouteImport } from "./routes/_loggedin/assessments/organizational/$evaluationId/index"
import { Route as LoggedinAssessmentsCapacityEvaluationIdIndexRouteImport } from "./routes/_loggedin/assessments/capacity/$evaluationId/index"
import { Route as LoggedinAssessmentsRiskEvaluationIdSummaryRouteImport } from "./routes/_loggedin/assessments/risk/$evaluationId/summary"
import { Route as LoggedinAssessmentsRiskEvaluationIdMitigationRouteImport } from "./routes/_loggedin/assessments/risk/$evaluationId/mitigation"
import { Route as LoggedinAssessmentsOrganizationalEvaluationIdSummaryRouteImport } from "./routes/_loggedin/assessments/organizational/$evaluationId/summary"
import { Route as LoggedinAssessmentsCapacityEvaluationIdSummaryRouteImport } from "./routes/_loggedin/assessments/capacity/$evaluationId/summary"
import { Route as LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRouteImport } from "./routes/_loggedin/assessments/organizational/$evaluationId/action-plan/index"
import { Route as LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRouteImport } from "./routes/_loggedin/assessments/capacity/$evaluationId/action-plan/index"
import { Route as LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRouteImport } from "./routes/_loggedin/assessments/risk/$evaluationId/principle/$number"
import { Route as LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRouteImport } from "./routes/_loggedin/assessments/organizational/$evaluationId/dimension/$number"
import { Route as LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRouteImport } from "./routes/_loggedin/assessments/organizational/$evaluationId/action-plan/$measureId"
import { Route as LoggedinAssessmentsCapacityEvaluationIdAreaNumberRouteImport } from "./routes/_loggedin/assessments/capacity/$evaluationId/area/$number"
import { Route as LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRouteImport } from "./routes/_loggedin/assessments/capacity/$evaluationId/action-plan/$measureId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedinRoute = LoggedinRouteImport.update({
  id: "/_loggedin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedinAssessmentsIndexRoute =
  LoggedinAssessmentsIndexRouteImport.update({
    id: "/assessments/",
    path: "/assessments/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsUsersRoute =
  LoggedinAssessmentsUsersRouteImport.update({
    id: "/assessments/users",
    path: "/assessments/users",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsOrganisationsRoute =
  LoggedinAssessmentsOrganisationsRouteImport.update({
    id: "/assessments/organisations",
    path: "/assessments/organisations",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsNewRoute = LoggedinAssessmentsNewRouteImport.update({
  id: "/assessments/new",
  path: "/assessments/new",
  getParentRoute: () => LoggedinRoute,
} as any)
const LoggedinAssessmentsDashboardRoute =
  LoggedinAssessmentsDashboardRouteImport.update({
    id: "/assessments/dashboard",
    path: "/assessments/dashboard",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsAnalyticsRoute =
  LoggedinAssessmentsAnalyticsRouteImport.update({
    id: "/assessments/analytics",
    path: "/assessments/analytics",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsAdminGlobalRoute =
  LoggedinAssessmentsAdminGlobalRouteImport.update({
    id: "/assessments/admin-global",
    path: "/assessments/admin-global",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsRiskIndexRoute =
  LoggedinAssessmentsRiskIndexRouteImport.update({
    id: "/assessments/risk/",
    path: "/assessments/risk/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsOrganizationalIndexRoute =
  LoggedinAssessmentsOrganizationalIndexRouteImport.update({
    id: "/assessments/organizational/",
    path: "/assessments/organizational/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsCapacityIndexRoute =
  LoggedinAssessmentsCapacityIndexRouteImport.update({
    id: "/assessments/capacity/",
    path: "/assessments/capacity/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsRiskAdminRoute =
  LoggedinAssessmentsRiskAdminRouteImport.update({
    id: "/assessments/risk/admin",
    path: "/assessments/risk/admin",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsOrganizationalAdminRoute =
  LoggedinAssessmentsOrganizationalAdminRouteImport.update({
    id: "/assessments/organizational/admin",
    path: "/assessments/organizational/admin",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsCapacityAdminRoute =
  LoggedinAssessmentsCapacityAdminRouteImport.update({
    id: "/assessments/capacity/admin",
    path: "/assessments/capacity/admin",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsAssociationsProfileIdRoute =
  LoggedinAssessmentsAssociationsProfileIdRouteImport.update({
    id: "/assessments/associations/$profileId",
    path: "/assessments/associations/$profileId",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsProfileIdEditRoute =
  LoggedinAssessmentsProfileIdEditRouteImport.update({
    id: "/assessments/$profileId/edit",
    path: "/assessments/$profileId/edit",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsRiskEvaluationIdIndexRoute =
  LoggedinAssessmentsRiskEvaluationIdIndexRouteImport.update({
    id: "/assessments/risk/$evaluationId/",
    path: "/assessments/risk/$evaluationId/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute =
  LoggedinAssessmentsOrganizationalEvaluationIdIndexRouteImport.update({
    id: "/assessments/organizational/$evaluationId/",
    path: "/assessments/organizational/$evaluationId/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsCapacityEvaluationIdIndexRoute =
  LoggedinAssessmentsCapacityEvaluationIdIndexRouteImport.update({
    id: "/assessments/capacity/$evaluationId/",
    path: "/assessments/capacity/$evaluationId/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsRiskEvaluationIdSummaryRoute =
  LoggedinAssessmentsRiskEvaluationIdSummaryRouteImport.update({
    id: "/assessments/risk/$evaluationId/summary",
    path: "/assessments/risk/$evaluationId/summary",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsRiskEvaluationIdMitigationRoute =
  LoggedinAssessmentsRiskEvaluationIdMitigationRouteImport.update({
    id: "/assessments/risk/$evaluationId/mitigation",
    path: "/assessments/risk/$evaluationId/mitigation",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute =
  LoggedinAssessmentsOrganizationalEvaluationIdSummaryRouteImport.update({
    id: "/assessments/organizational/$evaluationId/summary",
    path: "/assessments/organizational/$evaluationId/summary",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsCapacityEvaluationIdSummaryRoute =
  LoggedinAssessmentsCapacityEvaluationIdSummaryRouteImport.update({
    id: "/assessments/capacity/$evaluationId/summary",
    path: "/assessments/capacity/$evaluationId/summary",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute =
  LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRouteImport.update(
    {
      id: "/assessments/organizational/$evaluationId/action-plan/",
      path: "/assessments/organizational/$evaluationId/action-plan/",
      getParentRoute: () => LoggedinRoute,
    } as any,
  )
const LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute =
  LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRouteImport.update({
    id: "/assessments/capacity/$evaluationId/action-plan/",
    path: "/assessments/capacity/$evaluationId/action-plan/",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute =
  LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRouteImport.update({
    id: "/assessments/risk/$evaluationId/principle/$number",
    path: "/assessments/risk/$evaluationId/principle/$number",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute =
  LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRouteImport.update(
    {
      id: "/assessments/organizational/$evaluationId/dimension/$number",
      path: "/assessments/organizational/$evaluationId/dimension/$number",
      getParentRoute: () => LoggedinRoute,
    } as any,
  )
const LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute =
  LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRouteImport.update(
    {
      id: "/assessments/organizational/$evaluationId/action-plan/$measureId",
      path: "/assessments/organizational/$evaluationId/action-plan/$measureId",
      getParentRoute: () => LoggedinRoute,
    } as any,
  )
const LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute =
  LoggedinAssessmentsCapacityEvaluationIdAreaNumberRouteImport.update({
    id: "/assessments/capacity/$evaluationId/area/$number",
    path: "/assessments/capacity/$evaluationId/area/$number",
    getParentRoute: () => LoggedinRoute,
  } as any)
const LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute =
  LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRouteImport.update({
    id: "/assessments/capacity/$evaluationId/action-plan/$measureId",
    path: "/assessments/capacity/$evaluationId/action-plan/$measureId",
    getParentRoute: () => LoggedinRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/assessments/admin-global": typeof LoggedinAssessmentsAdminGlobalRoute
  "/assessments/analytics": typeof LoggedinAssessmentsAnalyticsRoute
  "/assessments/dashboard": typeof LoggedinAssessmentsDashboardRoute
  "/assessments/new": typeof LoggedinAssessmentsNewRoute
  "/assessments/organisations": typeof LoggedinAssessmentsOrganisationsRoute
  "/assessments/users": typeof LoggedinAssessmentsUsersRoute
  "/assessments/": typeof LoggedinAssessmentsIndexRoute
  "/assessments/$profileId/edit": typeof LoggedinAssessmentsProfileIdEditRoute
  "/assessments/associations/$profileId": typeof LoggedinAssessmentsAssociationsProfileIdRoute
  "/assessments/capacity/admin": typeof LoggedinAssessmentsCapacityAdminRoute
  "/assessments/organizational/admin": typeof LoggedinAssessmentsOrganizationalAdminRoute
  "/assessments/risk/admin": typeof LoggedinAssessmentsRiskAdminRoute
  "/assessments/capacity/": typeof LoggedinAssessmentsCapacityIndexRoute
  "/assessments/organizational/": typeof LoggedinAssessmentsOrganizationalIndexRoute
  "/assessments/risk/": typeof LoggedinAssessmentsRiskIndexRoute
  "/assessments/capacity/$evaluationId/summary": typeof LoggedinAssessmentsCapacityEvaluationIdSummaryRoute
  "/assessments/organizational/$evaluationId/summary": typeof LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute
  "/assessments/risk/$evaluationId/mitigation": typeof LoggedinAssessmentsRiskEvaluationIdMitigationRoute
  "/assessments/risk/$evaluationId/summary": typeof LoggedinAssessmentsRiskEvaluationIdSummaryRoute
  "/assessments/capacity/$evaluationId/": typeof LoggedinAssessmentsCapacityEvaluationIdIndexRoute
  "/assessments/organizational/$evaluationId/": typeof LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute
  "/assessments/risk/$evaluationId/": typeof LoggedinAssessmentsRiskEvaluationIdIndexRoute
  "/assessments/capacity/$evaluationId/action-plan/$measureId": typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute
  "/assessments/capacity/$evaluationId/area/$number": typeof LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute
  "/assessments/organizational/$evaluationId/action-plan/$measureId": typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute
  "/assessments/organizational/$evaluationId/dimension/$number": typeof LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute
  "/assessments/risk/$evaluationId/principle/$number": typeof LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute
  "/assessments/capacity/$evaluationId/action-plan/": typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute
  "/assessments/organizational/$evaluationId/action-plan/": typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/assessments/admin-global": typeof LoggedinAssessmentsAdminGlobalRoute
  "/assessments/analytics": typeof LoggedinAssessmentsAnalyticsRoute
  "/assessments/dashboard": typeof LoggedinAssessmentsDashboardRoute
  "/assessments/new": typeof LoggedinAssessmentsNewRoute
  "/assessments/organisations": typeof LoggedinAssessmentsOrganisationsRoute
  "/assessments/users": typeof LoggedinAssessmentsUsersRoute
  "/assessments": typeof LoggedinAssessmentsIndexRoute
  "/assessments/$profileId/edit": typeof LoggedinAssessmentsProfileIdEditRoute
  "/assessments/associations/$profileId": typeof LoggedinAssessmentsAssociationsProfileIdRoute
  "/assessments/capacity/admin": typeof LoggedinAssessmentsCapacityAdminRoute
  "/assessments/organizational/admin": typeof LoggedinAssessmentsOrganizationalAdminRoute
  "/assessments/risk/admin": typeof LoggedinAssessmentsRiskAdminRoute
  "/assessments/capacity": typeof LoggedinAssessmentsCapacityIndexRoute
  "/assessments/organizational": typeof LoggedinAssessmentsOrganizationalIndexRoute
  "/assessments/risk": typeof LoggedinAssessmentsRiskIndexRoute
  "/assessments/capacity/$evaluationId/summary": typeof LoggedinAssessmentsCapacityEvaluationIdSummaryRoute
  "/assessments/organizational/$evaluationId/summary": typeof LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute
  "/assessments/risk/$evaluationId/mitigation": typeof LoggedinAssessmentsRiskEvaluationIdMitigationRoute
  "/assessments/risk/$evaluationId/summary": typeof LoggedinAssessmentsRiskEvaluationIdSummaryRoute
  "/assessments/capacity/$evaluationId": typeof LoggedinAssessmentsCapacityEvaluationIdIndexRoute
  "/assessments/organizational/$evaluationId": typeof LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute
  "/assessments/risk/$evaluationId": typeof LoggedinAssessmentsRiskEvaluationIdIndexRoute
  "/assessments/capacity/$evaluationId/action-plan/$measureId": typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute
  "/assessments/capacity/$evaluationId/area/$number": typeof LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute
  "/assessments/organizational/$evaluationId/action-plan/$measureId": typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute
  "/assessments/organizational/$evaluationId/dimension/$number": typeof LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute
  "/assessments/risk/$evaluationId/principle/$number": typeof LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute
  "/assessments/capacity/$evaluationId/action-plan": typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute
  "/assessments/organizational/$evaluationId/action-plan": typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_loggedin": typeof LoggedinRouteWithChildren
  "/login": typeof LoginRoute
  "/_loggedin/assessments/admin-global": typeof LoggedinAssessmentsAdminGlobalRoute
  "/_loggedin/assessments/analytics": typeof LoggedinAssessmentsAnalyticsRoute
  "/_loggedin/assessments/dashboard": typeof LoggedinAssessmentsDashboardRoute
  "/_loggedin/assessments/new": typeof LoggedinAssessmentsNewRoute
  "/_loggedin/assessments/organisations": typeof LoggedinAssessmentsOrganisationsRoute
  "/_loggedin/assessments/users": typeof LoggedinAssessmentsUsersRoute
  "/_loggedin/assessments/": typeof LoggedinAssessmentsIndexRoute
  "/_loggedin/assessments/$profileId/edit": typeof LoggedinAssessmentsProfileIdEditRoute
  "/_loggedin/assessments/associations/$profileId": typeof LoggedinAssessmentsAssociationsProfileIdRoute
  "/_loggedin/assessments/capacity/admin": typeof LoggedinAssessmentsCapacityAdminRoute
  "/_loggedin/assessments/organizational/admin": typeof LoggedinAssessmentsOrganizationalAdminRoute
  "/_loggedin/assessments/risk/admin": typeof LoggedinAssessmentsRiskAdminRoute
  "/_loggedin/assessments/capacity/": typeof LoggedinAssessmentsCapacityIndexRoute
  "/_loggedin/assessments/organizational/": typeof LoggedinAssessmentsOrganizationalIndexRoute
  "/_loggedin/assessments/risk/": typeof LoggedinAssessmentsRiskIndexRoute
  "/_loggedin/assessments/capacity/$evaluationId/summary": typeof LoggedinAssessmentsCapacityEvaluationIdSummaryRoute
  "/_loggedin/assessments/organizational/$evaluationId/summary": typeof LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute
  "/_loggedin/assessments/risk/$evaluationId/mitigation": typeof LoggedinAssessmentsRiskEvaluationIdMitigationRoute
  "/_loggedin/assessments/risk/$evaluationId/summary": typeof LoggedinAssessmentsRiskEvaluationIdSummaryRoute
  "/_loggedin/assessments/capacity/$evaluationId/": typeof LoggedinAssessmentsCapacityEvaluationIdIndexRoute
  "/_loggedin/assessments/organizational/$evaluationId/": typeof LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute
  "/_loggedin/assessments/risk/$evaluationId/": typeof LoggedinAssessmentsRiskEvaluationIdIndexRoute
  "/_loggedin/assessments/capacity/$evaluationId/action-plan/$measureId": typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute
  "/_loggedin/assessments/capacity/$evaluationId/area/$number": typeof LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute
  "/_loggedin/assessments/organizational/$evaluationId/action-plan/$measureId": typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute
  "/_loggedin/assessments/organizational/$evaluationId/dimension/$number": typeof LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute
  "/_loggedin/assessments/risk/$evaluationId/principle/$number": typeof LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute
  "/_loggedin/assessments/capacity/$evaluationId/action-plan/": typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute
  "/_loggedin/assessments/organizational/$evaluationId/action-plan/": typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/assessments/admin-global"
    | "/assessments/analytics"
    | "/assessments/dashboard"
    | "/assessments/new"
    | "/assessments/organisations"
    | "/assessments/users"
    | "/assessments/"
    | "/assessments/$profileId/edit"
    | "/assessments/associations/$profileId"
    | "/assessments/capacity/admin"
    | "/assessments/organizational/admin"
    | "/assessments/risk/admin"
    | "/assessments/capacity/"
    | "/assessments/organizational/"
    | "/assessments/risk/"
    | "/assessments/capacity/$evaluationId/summary"
    | "/assessments/organizational/$evaluationId/summary"
    | "/assessments/risk/$evaluationId/mitigation"
    | "/assessments/risk/$evaluationId/summary"
    | "/assessments/capacity/$evaluationId/"
    | "/assessments/organizational/$evaluationId/"
    | "/assessments/risk/$evaluationId/"
    | "/assessments/capacity/$evaluationId/action-plan/$measureId"
    | "/assessments/capacity/$evaluationId/area/$number"
    | "/assessments/organizational/$evaluationId/action-plan/$measureId"
    | "/assessments/organizational/$evaluationId/dimension/$number"
    | "/assessments/risk/$evaluationId/principle/$number"
    | "/assessments/capacity/$evaluationId/action-plan/"
    | "/assessments/organizational/$evaluationId/action-plan/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/assessments/admin-global"
    | "/assessments/analytics"
    | "/assessments/dashboard"
    | "/assessments/new"
    | "/assessments/organisations"
    | "/assessments/users"
    | "/assessments"
    | "/assessments/$profileId/edit"
    | "/assessments/associations/$profileId"
    | "/assessments/capacity/admin"
    | "/assessments/organizational/admin"
    | "/assessments/risk/admin"
    | "/assessments/capacity"
    | "/assessments/organizational"
    | "/assessments/risk"
    | "/assessments/capacity/$evaluationId/summary"
    | "/assessments/organizational/$evaluationId/summary"
    | "/assessments/risk/$evaluationId/mitigation"
    | "/assessments/risk/$evaluationId/summary"
    | "/assessments/capacity/$evaluationId"
    | "/assessments/organizational/$evaluationId"
    | "/assessments/risk/$evaluationId"
    | "/assessments/capacity/$evaluationId/action-plan/$measureId"
    | "/assessments/capacity/$evaluationId/area/$number"
    | "/assessments/organizational/$evaluationId/action-plan/$measureId"
    | "/assessments/organizational/$evaluationId/dimension/$number"
    | "/assessments/risk/$evaluationId/principle/$number"
    | "/assessments/capacity/$evaluationId/action-plan"
    | "/assessments/organizational/$evaluationId/action-plan"
  id:
    | "__root__"
    | "/"
    | "/_loggedin"
    | "/login"
    | "/_loggedin/assessments/admin-global"
    | "/_loggedin/assessments/analytics"
    | "/_loggedin/assessments/dashboard"
    | "/_loggedin/assessments/new"
    | "/_loggedin/assessments/organisations"
    | "/_loggedin/assessments/users"
    | "/_loggedin/assessments/"
    | "/_loggedin/assessments/$profileId/edit"
    | "/_loggedin/assessments/associations/$profileId"
    | "/_loggedin/assessments/capacity/admin"
    | "/_loggedin/assessments/organizational/admin"
    | "/_loggedin/assessments/risk/admin"
    | "/_loggedin/assessments/capacity/"
    | "/_loggedin/assessments/organizational/"
    | "/_loggedin/assessments/risk/"
    | "/_loggedin/assessments/capacity/$evaluationId/summary"
    | "/_loggedin/assessments/organizational/$evaluationId/summary"
    | "/_loggedin/assessments/risk/$evaluationId/mitigation"
    | "/_loggedin/assessments/risk/$evaluationId/summary"
    | "/_loggedin/assessments/capacity/$evaluationId/"
    | "/_loggedin/assessments/organizational/$evaluationId/"
    | "/_loggedin/assessments/risk/$evaluationId/"
    | "/_loggedin/assessments/capacity/$evaluationId/action-plan/$measureId"
    | "/_loggedin/assessments/capacity/$evaluationId/area/$number"
    | "/_loggedin/assessments/organizational/$evaluationId/action-plan/$measureId"
    | "/_loggedin/assessments/organizational/$evaluationId/dimension/$number"
    | "/_loggedin/assessments/risk/$evaluationId/principle/$number"
    | "/_loggedin/assessments/capacity/$evaluationId/action-plan/"
    | "/_loggedin/assessments/organizational/$evaluationId/action-plan/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoggedinRoute: typeof LoggedinRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_loggedin": {
      id: "/_loggedin"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LoggedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_loggedin/assessments/": {
      id: "/_loggedin/assessments/"
      path: "/assessments"
      fullPath: "/assessments/"
      preLoaderRoute: typeof LoggedinAssessmentsIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/users": {
      id: "/_loggedin/assessments/users"
      path: "/assessments/users"
      fullPath: "/assessments/users"
      preLoaderRoute: typeof LoggedinAssessmentsUsersRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organisations": {
      id: "/_loggedin/assessments/organisations"
      path: "/assessments/organisations"
      fullPath: "/assessments/organisations"
      preLoaderRoute: typeof LoggedinAssessmentsOrganisationsRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/new": {
      id: "/_loggedin/assessments/new"
      path: "/assessments/new"
      fullPath: "/assessments/new"
      preLoaderRoute: typeof LoggedinAssessmentsNewRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/dashboard": {
      id: "/_loggedin/assessments/dashboard"
      path: "/assessments/dashboard"
      fullPath: "/assessments/dashboard"
      preLoaderRoute: typeof LoggedinAssessmentsDashboardRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/analytics": {
      id: "/_loggedin/assessments/analytics"
      path: "/assessments/analytics"
      fullPath: "/assessments/analytics"
      preLoaderRoute: typeof LoggedinAssessmentsAnalyticsRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/admin-global": {
      id: "/_loggedin/assessments/admin-global"
      path: "/assessments/admin-global"
      fullPath: "/assessments/admin-global"
      preLoaderRoute: typeof LoggedinAssessmentsAdminGlobalRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/risk/": {
      id: "/_loggedin/assessments/risk/"
      path: "/assessments/risk"
      fullPath: "/assessments/risk/"
      preLoaderRoute: typeof LoggedinAssessmentsRiskIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organizational/": {
      id: "/_loggedin/assessments/organizational/"
      path: "/assessments/organizational"
      fullPath: "/assessments/organizational/"
      preLoaderRoute: typeof LoggedinAssessmentsOrganizationalIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/capacity/": {
      id: "/_loggedin/assessments/capacity/"
      path: "/assessments/capacity"
      fullPath: "/assessments/capacity/"
      preLoaderRoute: typeof LoggedinAssessmentsCapacityIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/risk/admin": {
      id: "/_loggedin/assessments/risk/admin"
      path: "/assessments/risk/admin"
      fullPath: "/assessments/risk/admin"
      preLoaderRoute: typeof LoggedinAssessmentsRiskAdminRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organizational/admin": {
      id: "/_loggedin/assessments/organizational/admin"
      path: "/assessments/organizational/admin"
      fullPath: "/assessments/organizational/admin"
      preLoaderRoute: typeof LoggedinAssessmentsOrganizationalAdminRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/capacity/admin": {
      id: "/_loggedin/assessments/capacity/admin"
      path: "/assessments/capacity/admin"
      fullPath: "/assessments/capacity/admin"
      preLoaderRoute: typeof LoggedinAssessmentsCapacityAdminRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/associations/$profileId": {
      id: "/_loggedin/assessments/associations/$profileId"
      path: "/assessments/associations/$profileId"
      fullPath: "/assessments/associations/$profileId"
      preLoaderRoute: typeof LoggedinAssessmentsAssociationsProfileIdRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/$profileId/edit": {
      id: "/_loggedin/assessments/$profileId/edit"
      path: "/assessments/$profileId/edit"
      fullPath: "/assessments/$profileId/edit"
      preLoaderRoute: typeof LoggedinAssessmentsProfileIdEditRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/risk/$evaluationId/": {
      id: "/_loggedin/assessments/risk/$evaluationId/"
      path: "/assessments/risk/$evaluationId"
      fullPath: "/assessments/risk/$evaluationId/"
      preLoaderRoute: typeof LoggedinAssessmentsRiskEvaluationIdIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organizational/$evaluationId/": {
      id: "/_loggedin/assessments/organizational/$evaluationId/"
      path: "/assessments/organizational/$evaluationId"
      fullPath: "/assessments/organizational/$evaluationId/"
      preLoaderRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/capacity/$evaluationId/": {
      id: "/_loggedin/assessments/capacity/$evaluationId/"
      path: "/assessments/capacity/$evaluationId"
      fullPath: "/assessments/capacity/$evaluationId/"
      preLoaderRoute: typeof LoggedinAssessmentsCapacityEvaluationIdIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/risk/$evaluationId/summary": {
      id: "/_loggedin/assessments/risk/$evaluationId/summary"
      path: "/assessments/risk/$evaluationId/summary"
      fullPath: "/assessments/risk/$evaluationId/summary"
      preLoaderRoute: typeof LoggedinAssessmentsRiskEvaluationIdSummaryRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/risk/$evaluationId/mitigation": {
      id: "/_loggedin/assessments/risk/$evaluationId/mitigation"
      path: "/assessments/risk/$evaluationId/mitigation"
      fullPath: "/assessments/risk/$evaluationId/mitigation"
      preLoaderRoute: typeof LoggedinAssessmentsRiskEvaluationIdMitigationRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organizational/$evaluationId/summary": {
      id: "/_loggedin/assessments/organizational/$evaluationId/summary"
      path: "/assessments/organizational/$evaluationId/summary"
      fullPath: "/assessments/organizational/$evaluationId/summary"
      preLoaderRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdSummaryRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/capacity/$evaluationId/summary": {
      id: "/_loggedin/assessments/capacity/$evaluationId/summary"
      path: "/assessments/capacity/$evaluationId/summary"
      fullPath: "/assessments/capacity/$evaluationId/summary"
      preLoaderRoute: typeof LoggedinAssessmentsCapacityEvaluationIdSummaryRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organizational/$evaluationId/action-plan/": {
      id: "/_loggedin/assessments/organizational/$evaluationId/action-plan/"
      path: "/assessments/organizational/$evaluationId/action-plan"
      fullPath: "/assessments/organizational/$evaluationId/action-plan/"
      preLoaderRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/capacity/$evaluationId/action-plan/": {
      id: "/_loggedin/assessments/capacity/$evaluationId/action-plan/"
      path: "/assessments/capacity/$evaluationId/action-plan"
      fullPath: "/assessments/capacity/$evaluationId/action-plan/"
      preLoaderRoute: typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/risk/$evaluationId/principle/$number": {
      id: "/_loggedin/assessments/risk/$evaluationId/principle/$number"
      path: "/assessments/risk/$evaluationId/principle/$number"
      fullPath: "/assessments/risk/$evaluationId/principle/$number"
      preLoaderRoute: typeof LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organizational/$evaluationId/dimension/$number": {
      id: "/_loggedin/assessments/organizational/$evaluationId/dimension/$number"
      path: "/assessments/organizational/$evaluationId/dimension/$number"
      fullPath: "/assessments/organizational/$evaluationId/dimension/$number"
      preLoaderRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/organizational/$evaluationId/action-plan/$measureId": {
      id: "/_loggedin/assessments/organizational/$evaluationId/action-plan/$measureId"
      path: "/assessments/organizational/$evaluationId/action-plan/$measureId"
      fullPath: "/assessments/organizational/$evaluationId/action-plan/$measureId"
      preLoaderRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/capacity/$evaluationId/area/$number": {
      id: "/_loggedin/assessments/capacity/$evaluationId/area/$number"
      path: "/assessments/capacity/$evaluationId/area/$number"
      fullPath: "/assessments/capacity/$evaluationId/area/$number"
      preLoaderRoute: typeof LoggedinAssessmentsCapacityEvaluationIdAreaNumberRouteImport
      parentRoute: typeof LoggedinRoute
    }
    "/_loggedin/assessments/capacity/$evaluationId/action-plan/$measureId": {
      id: "/_loggedin/assessments/capacity/$evaluationId/action-plan/$measureId"
      path: "/assessments/capacity/$evaluationId/action-plan/$measureId"
      fullPath: "/assessments/capacity/$evaluationId/action-plan/$measureId"
      preLoaderRoute: typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRouteImport
      parentRoute: typeof LoggedinRoute
    }
  }
}

interface LoggedinRouteChildren {
  LoggedinAssessmentsAdminGlobalRoute: typeof LoggedinAssessmentsAdminGlobalRoute
  LoggedinAssessmentsAnalyticsRoute: typeof LoggedinAssessmentsAnalyticsRoute
  LoggedinAssessmentsDashboardRoute: typeof LoggedinAssessmentsDashboardRoute
  LoggedinAssessmentsNewRoute: typeof LoggedinAssessmentsNewRoute
  LoggedinAssessmentsOrganisationsRoute: typeof LoggedinAssessmentsOrganisationsRoute
  LoggedinAssessmentsUsersRoute: typeof LoggedinAssessmentsUsersRoute
  LoggedinAssessmentsIndexRoute: typeof LoggedinAssessmentsIndexRoute
  LoggedinAssessmentsProfileIdEditRoute: typeof LoggedinAssessmentsProfileIdEditRoute
  LoggedinAssessmentsAssociationsProfileIdRoute: typeof LoggedinAssessmentsAssociationsProfileIdRoute
  LoggedinAssessmentsCapacityAdminRoute: typeof LoggedinAssessmentsCapacityAdminRoute
  LoggedinAssessmentsOrganizationalAdminRoute: typeof LoggedinAssessmentsOrganizationalAdminRoute
  LoggedinAssessmentsRiskAdminRoute: typeof LoggedinAssessmentsRiskAdminRoute
  LoggedinAssessmentsCapacityIndexRoute: typeof LoggedinAssessmentsCapacityIndexRoute
  LoggedinAssessmentsOrganizationalIndexRoute: typeof LoggedinAssessmentsOrganizationalIndexRoute
  LoggedinAssessmentsRiskIndexRoute: typeof LoggedinAssessmentsRiskIndexRoute
  LoggedinAssessmentsCapacityEvaluationIdSummaryRoute: typeof LoggedinAssessmentsCapacityEvaluationIdSummaryRoute
  LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute
  LoggedinAssessmentsRiskEvaluationIdMitigationRoute: typeof LoggedinAssessmentsRiskEvaluationIdMitigationRoute
  LoggedinAssessmentsRiskEvaluationIdSummaryRoute: typeof LoggedinAssessmentsRiskEvaluationIdSummaryRoute
  LoggedinAssessmentsCapacityEvaluationIdIndexRoute: typeof LoggedinAssessmentsCapacityEvaluationIdIndexRoute
  LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute
  LoggedinAssessmentsRiskEvaluationIdIndexRoute: typeof LoggedinAssessmentsRiskEvaluationIdIndexRoute
  LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute: typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute
  LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute: typeof LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute
  LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute
  LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute
  LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute: typeof LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute
  LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute: typeof LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute
  LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute: typeof LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute
}

const LoggedinRouteChildren: LoggedinRouteChildren = {
  LoggedinAssessmentsAdminGlobalRoute: LoggedinAssessmentsAdminGlobalRoute,
  LoggedinAssessmentsAnalyticsRoute: LoggedinAssessmentsAnalyticsRoute,
  LoggedinAssessmentsDashboardRoute: LoggedinAssessmentsDashboardRoute,
  LoggedinAssessmentsNewRoute: LoggedinAssessmentsNewRoute,
  LoggedinAssessmentsOrganisationsRoute: LoggedinAssessmentsOrganisationsRoute,
  LoggedinAssessmentsUsersRoute: LoggedinAssessmentsUsersRoute,
  LoggedinAssessmentsIndexRoute: LoggedinAssessmentsIndexRoute,
  LoggedinAssessmentsProfileIdEditRoute: LoggedinAssessmentsProfileIdEditRoute,
  LoggedinAssessmentsAssociationsProfileIdRoute:
    LoggedinAssessmentsAssociationsProfileIdRoute,
  LoggedinAssessmentsCapacityAdminRoute: LoggedinAssessmentsCapacityAdminRoute,
  LoggedinAssessmentsOrganizationalAdminRoute:
    LoggedinAssessmentsOrganizationalAdminRoute,
  LoggedinAssessmentsRiskAdminRoute: LoggedinAssessmentsRiskAdminRoute,
  LoggedinAssessmentsCapacityIndexRoute: LoggedinAssessmentsCapacityIndexRoute,
  LoggedinAssessmentsOrganizationalIndexRoute:
    LoggedinAssessmentsOrganizationalIndexRoute,
  LoggedinAssessmentsRiskIndexRoute: LoggedinAssessmentsRiskIndexRoute,
  LoggedinAssessmentsCapacityEvaluationIdSummaryRoute:
    LoggedinAssessmentsCapacityEvaluationIdSummaryRoute,
  LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute:
    LoggedinAssessmentsOrganizationalEvaluationIdSummaryRoute,
  LoggedinAssessmentsRiskEvaluationIdMitigationRoute:
    LoggedinAssessmentsRiskEvaluationIdMitigationRoute,
  LoggedinAssessmentsRiskEvaluationIdSummaryRoute:
    LoggedinAssessmentsRiskEvaluationIdSummaryRoute,
  LoggedinAssessmentsCapacityEvaluationIdIndexRoute:
    LoggedinAssessmentsCapacityEvaluationIdIndexRoute,
  LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute:
    LoggedinAssessmentsOrganizationalEvaluationIdIndexRoute,
  LoggedinAssessmentsRiskEvaluationIdIndexRoute:
    LoggedinAssessmentsRiskEvaluationIdIndexRoute,
  LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute:
    LoggedinAssessmentsCapacityEvaluationIdActionPlanMeasureIdRoute,
  LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute:
    LoggedinAssessmentsCapacityEvaluationIdAreaNumberRoute,
  LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute:
    LoggedinAssessmentsOrganizationalEvaluationIdActionPlanMeasureIdRoute,
  LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute:
    LoggedinAssessmentsOrganizationalEvaluationIdDimensionNumberRoute,
  LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute:
    LoggedinAssessmentsRiskEvaluationIdPrincipleNumberRoute,
  LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute:
    LoggedinAssessmentsCapacityEvaluationIdActionPlanIndexRoute,
  LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute:
    LoggedinAssessmentsOrganizationalEvaluationIdActionPlanIndexRoute,
}

const LoggedinRouteWithChildren = LoggedinRoute._addFileChildren(
  LoggedinRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoggedinRoute: LoggedinRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
